name: CI

on:
  push:
    branches: [ release/5.0 ]
  workflow_dispatch:

jobs:
  build-runtime-and-tests:
    env:
      ROOTFS_ENV: ROOTFS_DIR=/crossrootfs/x64
      DOTNET_DOCKER_SERVER: mcr.microsoft.com/dotnet-buildtools/prereqs
      DOTNET_DOCKER_FALLBACK_TAG: ubuntu-18.04-cross-freebsd-20201102145728-f13d79e
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{GITHUB_REF#refs/heads/}}
          token: ${{ secrets.checkoutsec }}
        
      - name: Get Latest Docker for FreeBSD
        run: |
          curl https://raw.githubusercontent.com/dotnet/versions/master/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-master.json -o /tmp/images.json
          LATEST_TAG=$(node -p "require('/tmp/images.json').repos[0].images.find(x => x.platforms[0].dockerfile.includes('freebsd')).platforms[0].simpleTags[0]" 2>/dev/null)
          echo "DOTNET_DOCKER_TAG=$DOTNET_DOCKER_SERVER:${LATEST_TAG:-DOTNET_DOCKER_FALLBACK_TAG}" >> $GITHUB_ENV

      - name: Build Runtime Linux->FreeBSD
        run: docker run -e $ROOTFS_ENV -v $(pwd):/runtime $DOTNET_DOCKER_TAG /runtime/build.sh -c Release -cross -os freebsd
        
      - name: Build Runtime Tests but do not run them Linux->FreeBSD
        run: docker run -e $ROOTFS_ENV -v $(pwd):/runtime $DOTNET_DOCKER_TAG /runtime/build.sh -c Release -cross -os freebsd -subset Libs.Tests /p:ArchiveTests=true
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/packages/Release/Shipping/
